### ISSUE TITLE
Buggino lista oggetti di scena

### ISSUE THREAD

**Issue by mikyll** [Federicoand98/PathTracing#2]
Se un submenu è vuoto, quando questo viene aperto, viene aggiunta la entry successiva come submenu

![image](https://github.com/Federicoand98/PathTracing/assets/56556806/00b6fa03-e30a-4c99-89b9-8eed8fe0c3e1)

**Comment by Federicoand98** [comment]
mi ero dimenticato un if nella gui :)))))))))))))

**Comment by Federicoand98** [comment]
mi ero dimenticato un if nella gui :)))))))))))))
